---
- name: Install Glances
  hosts: 10.10.5.181  # Replace with the name of your target host or group
  become: no  # This allows the playbook to run with sudo privileges

  tasks:
    - name: Install Glances (Debian/Ubuntu)
      apt:
        name: glances
        state: present
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
