---
- name: Configure Windows Exporter
  hosts: 10.10.5.181
  become: yes
  tasks:
    - name: Set Python interpreter for Windows
      set_fact:
        ansible_python_interpreter: "C:\\path\\to\\python.exe"  # Replace with the actual path to Python on Windows
      delegate_to: 10.10.5.82  # This ensures the task runs on the control node
      run_once: yes

    - name: Create Windows Exporter Configuration File
      community.windows.win_ini_file:
        path: C:\path\to\your\config.ini
        section: ExporterSettings
        option: listen_address
        value: 0.0.0.0
