---
- name: Install and Configure Windows Exporter
  hosts: 10.10.5.181
  gather_facts: false

  tasks:
    - name: Download Windows Exporter ZIP
      win_get_url:
        url: "https://github.com/prometheus-community/windows_exporter/releases/download/v1.2.0/windows_exporter-1.2.0-amd64.zip"
        dest: "C:\Users\test"

    - name: Extract Windows Exporter ZIP
      win_unzip:
        src: "C:\\Temp\\windows_exporter.zip"
        dest: "C:\\Program Files\\Windows Exporter"
        creates: "C:\\Program Files\\Windows Exporter\\windows_exporter.exe"

    - name: Create Windows Exporter Service
      win_shell: |
        $serviceName = "windows_exporter"
        $executablePath = "C:\\Program Files\\Windows Exporter\\windows_exporter.exe"
        $arguments = "--collector.textfile.directory=C:\\Prometheus\\exporter_textfiles"

        New-Service -Name $serviceName -BinaryPathName "$executablePath $arguments" -DisplayName "Windows Exporter"
        Start-Service -Name $serviceName
      args:
        executable: powershell.exe

    - name: Add Firewall Rule for Windows Exporter
      win_shell: |
        New-NetFirewallRule -DisplayName "Windows Exporter" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 9182
      args:
        executable: powershell.exe
